version: "3.9"
services:
  pg:
    image: postgres:14.2
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: dimmaryanto93/udemy-springboot-app:latest
    ports: 
      - "8080:8080"
    environment:
      - DATABASE_HOST=pg
      - DATABASE_PORT=5432
      - DATABASE_NAME=database
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=password
      - APPLICATION_PORT=8080
    depends_on:
      - pg
  frontend:
    image: dimmaryanto93/udemy-angular-app:latest
    ports: 
      - "81:80"
    environment:
      - NGINX_ROOT_DOCUMENT=/var/www/html
      - BACKEND_HOST=backend
      - BACKEND_PORT=8080
      - BACKEND_CONTEXT_PATH=/
    depends_on:
      - backend
volumes:
  pg_data:


